# Generated by Django 5.0.4 on 2024-04-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                ("location", models.CharField(blank=True, max_length=30, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("salary", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
